### ISSUE TITLE
Soil seasonal sampling windows coding work

### ISSUE THREAD

**Issue by lstanish** [cflagg/codingSupportGroup#1]
@cflagg Round #1 of documents and code in the soilsWorkingCode folder. Have at it!

**Comment by cflagg** [comment]
### Goals
- Automated algorithm for identifying transitional temperature shifts per season per site 
- -------- for guiding when FOPS schedules soil core sampling. 
- Reproducible method (not eye-balling a graph)
- Quantitative (LOESS smoother? slope changes?)
- Module that can apply to multiple sites
- [future] how to do this with TIS data stream?

### Outline
- Munge together 2010 - 2015 files
- Standardize dates with either Julian dates or POSIX style
- First calculate a moving average, identify large "jumps" in moving average window 
- Data summary strategy for applying to multiple years? 
- -------- Average same day from multiple years? [will smooth out long-term temperature shifts]
- Apply LOESS to data set

### Initial Data
- Data corresponding to SERC in D02: http://www.wcc.nrcs.usda.gov/nwcc/site?sitenum=2039

**Comment by lstanish** [comment]
@cflagg Thanks for organizing my thoughts! 
- Good summary.

**Comment by cflagg** [comment]
Sarah had a good point in her emails about the phenopix package: this has been done before and quite numerously. 

Should explore phenology literature and determine if there is an established or applicable methodology for soil sampling (or at least for quantitatively identifying seasonal transitions).

**Comment by lstanish** [comment]
Agreed. At a minimum the phenology approach could be modified for soil transitions. It will take some time to read up on this, closing this issue for now.

**Comment by cflagg** [comment]
Sounds good. At a minimum I can code up a skeleton (pseudo-code, minimally) that will munge and order the data for whatever method we decide to use.
